---
server:
  port: 9015

postgres-url: jdbc:postgresql://${POSTGRES_ADDRESS:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:vk_forwarder_bot}

spring:
  datasource:
    url: ${postgres-url}
    username: ${POSTGRES_APP_USER:d}
    password: ${POSTGRES_APP_PASSWORD:d}

forwarder:
  vk:
    token: ${FORWARDER_VK_TOKEN}
    user-id: ${FORWARDER_VK_USER_ID}
    username: ${FORWARDER_VK_USERNAME}
    password: ${FORWARDER_VK_PASSWORD}
  tg:
    token: ${FORWARDER_TG_TOKEN}
    bot-username: ${FORWARDER_TG_BOT_USERNAME}
  cache-dir-path: ${FORWARDER_CACHE_DIR_PATH:cache}
  yt-ylp-file-path: ${FORWARDER_YT_YLP_FILE_PATH:src/dev/yt-dlp.exe}
  debug:
    max-stories-to-process: 50
    manual-trigger-password: ${FORWARDER_DEBUG_MANUAL_TRIGGER_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    org.taonity.vkforwarderbot: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.beans: DEBUG
