version: '2.4'

services:
  # APP
  db:
    extends:
      file: db/docker-compose.yml
      service: db
    ports:
      - 49001:5432

  flyway:
    extends:
      file: flyway/docker-compose.yml
      service: flyway
    depends_on:
      db:
        condition: service_healthy

  app:
    extends:
      file: app/docker-compose.yml
      service: app
    depends_on:
      flyway:
        condition: service_completed_successfully

volumes:
  vk-forwarder-bot-volume-db:
  vk-forwarder-bot-volume-db-backup:
