version: '2.4'

services:
  app:
    image: generaltao725/vk-forwarder-bot:latest
    environment:
      - JDK_JAVA_OPTIONS=--add-opens java.base/java.lang=ALL-UNNAMED
    env_file:
      - ../.env
    volumes:
      - ./config:/config
      - ./cookies.netscape:/vk-forwarder-bot/cookies.netscape
    healthcheck:
      test: curl localhost:9015/actuator/health
      interval: 10s
      timeout: 10s
      retries: 100